version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: always

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    volumes:
      - ./api/.env:/app/.env
    restart: always

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      - REDIS_ADDR=redis:6379
      - WORKER_HOST=worker
      - WORKER_PORT=8081
    ports:
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared-code:/code
    depends_on:
      - redis
      - python-executor
      - javascript-executor
      - cpp-executor
      - csharp-executor

    restart: on-failure:5
    privileged: true
    init: true

  # Language-specific executor images
  python-executor:
    build:
      context: ./executors/python
    image: python-executor
    volumes:
      - shared-code:/code
    restart: "no"

  javascript-executor:
    build:
      context: ./executors/javascript
    image: javascript-executor
    volumes:
      - shared-code:/code
    restart: "no"

  cpp-executor:
    build:
      context: ./executors/cpp
    image: cpp-executor
    volumes:
      - shared-code:/code
    restart: "no"

  csharp-executor:
    build:
      context: ./executors/csharp
    image: csharp-executor
    volumes:
      - shared-code:/code
    restart: "no"

volumes:
  redis-data:
  shared-code:
